# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title two matrix mutiplication
#' @keywords internal 
#' @useDynLib o2plsda
eigenmult <- function(A, B) {
    .Call(`_o2plsda_eigenmult`, A, B)
}

#' @title three matrix mutiplication
#' @keywords internal 
#' @useDynLib o2plsda
eigenthree <- function(A, B, C) {
    .Call(`_o2plsda_eigenthree`, A, B, C)
}

#' @title trans matrix * matrix
#' @keywords internal 
#' @useDynLib o2plsda
AtA <- function(A) {
    .Call(`_o2plsda_AtA`, A)
}

#' @title sort string
#' @keywords internal 
#' @useDynLib o2plsda
sort_str <- function(strings) {
    .Call(`_o2plsda_sort_str`, strings)
}

#' @title sampling a vector
#' @keywords internal 
#' @useDynLib o2plsda
sample_cpp <- function(x, n) {
    .Call(`_o2plsda_sample_cpp`, x, n)
}

#' @title calculate RMSE
#' @keywords internal 
#' @useDynLib o2plsda
rcpp_rmse <- function(y, y_hat) {
    .Call(`_o2plsda_rcpp_rmse`, y, y_hat)
}

#' @title order a vector of sting
#' @keywords internal 
#' @useDynLib o2plsda
order_str <- function(x) {
    .Call(`_o2plsda_order_str`, x)
}

#' @title order a vector
#' @keywords internal 
#' @useDynLib o2plsda
order_cpp <- function(x) {
    .Call(`_o2plsda_order_cpp`, x)
}

#' @title split a vector
#' @keywords internal 
#' @useDynLib o2plsda
split_str <- function(x) {
    .Call(`_o2plsda_split_str`, x)
}

#' @title unlist a list
#' @keywords internal 
#' @useDynLib o2plsda
unlist_cpp <- function(list) {
    .Call(`_o2plsda_unlist_cpp`, list)
}

#' @title lapply sampling
#' @keywords internal 
#' @useDynLib o2plsda
sample_lapply <- function(X, n) {
    .Call(`_o2plsda_sample_lapply`, X, n)
}

#' @title MCCV sampling
#' @keywords internal 
#' @useDynLib o2plsda
getMCCV_cpp <- function(x, n) {
    .Call(`_o2plsda_getMCCV_cpp`, x, n)
}

#' @title sum square of a matrix
#' @keywords internal 
#' @useDynLib o2plsda
s2 <- function(x) {
    .Call(`_o2plsda_s2`, x)
}

#' @title calcualte the Q value
#' @keywords internal 
#' @useDynLib o2plsda
Q <- function(y, y_hat) {
    .Call(`_o2plsda_Q`, y, y_hat)
}

#' @title get the sd for a matrix
#' @keywords internal 
#' @useDynLib o2plsda
colsds <- function(X) {
    .Call(`_o2plsda_colsds`, X)
}

#' @title get the total values for a matrix
#' @keywords internal 
#' @useDynLib o2plsda
column_sums <- function(X) {
    .Call(`_o2plsda_column_sums`, X)
}

#' @title orthogonal scores algorithn of partial leat squares (opls) projection
#' @keywords internal 
#' @useDynLib o2plsda
opls <- function(X, Y, ncomp, maxiter, tol) {
    .Call(`_o2plsda_opls`, X, Y, ncomp, maxiter, tol)
}

