# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

eigenmult <- function(A, B) {
    .Call(`_o2plsda_eigenmult`, A, B)
}

eigenthree <- function(A, B, C) {
    .Call(`_o2plsda_eigenthree`, A, B, C)
}

AtA <- function(A) {
    .Call(`_o2plsda_AtA`, A)
}

sort_str <- function(strings) {
    .Call(`_o2plsda_sort_str`, strings)
}

sample_cpp <- function(x, n) {
    .Call(`_o2plsda_sample_cpp`, x, n)
}

rcpp_rmse <- function(y, y_hat) {
    .Call(`_o2plsda_rcpp_rmse`, y, y_hat)
}

order_str <- function(x) {
    .Call(`_o2plsda_order_str`, x)
}

order_cpp <- function(x) {
    .Call(`_o2plsda_order_cpp`, x)
}

split_str <- function(x) {
    .Call(`_o2plsda_split_str`, x)
}

unlist_cpp <- function(list) {
    .Call(`_o2plsda_unlist_cpp`, list)
}

sample_lapply <- function(X, n) {
    .Call(`_o2plsda_sample_lapply`, X, n)
}

getMCCV_cpp <- function(x, n) {
    .Call(`_o2plsda_getMCCV_cpp`, x, n)
}

s2 <- function(x) {
    .Call(`_o2plsda_s2`, x)
}

Q <- function(y, y_hat) {
    .Call(`_o2plsda_Q`, y, y_hat)
}

